import 'package:zencillo_helpers/zencillo_helpers.dart';
import 'package:zencillo_redeban/models/redeban_response.dart';

extension RedebanFormaPagoDetalleMapper on RedebanResponse {
  FormaPagoDetalleModel toFormaPagoDetalle({
    required int idTurno,
    required int numeroTurno,
    required int idDocument,
    required double total,
    required double taxTotal,
    required double subTotal,
    required int idFormaPago,
  }) {
    final result = FormaPagoDetalleModel(
      idVenta: idDocument,
      idTurno: idTurno,
      identificacionRed: 'REDEBAN',
      codigoRespuestaActor: '',
      mensajeRespuesta: data,
      secuencialTransaccion: int.parse(numeroRecibo),
      numeroLote: numeroTurno,
      horaTransaccion: DateTime.now().getHourWindDev(),
      fechaTransaccion: DateTime.now(),
      numeroAutorizacion: numeroConfirmacion.limit(10),
      tid: '',
      mid: numeroConfirmacion.limit(10),
      valorInteres: 0,
      mensajeImpresion: '',
      codigoBanco: 0,
      nombreBanco: franquicia,
      nombreGrupoTarjeta: franquicia,
      modoLectura: '',
      nombreTarjetaHabiente: franquicia,
      montoFijo: '',
      identificadorAplicacion: '',
      aid: '',
      tipoCrigtograma: '',
      pin: '',
      arqc: '',
      numeroTarjetaTruncado: ultimosDigitosTarjeta,
      fechaVencimientoTarjeta: 0,
      numeroTarjetaEncriptada: ultimosDigitosTarjeta,
      impuesto: taxTotal,
      baseConImpuesto: subTotal + taxTotal,
      baseSinImpuesto: subTotal,
      montoImpuesto: taxTotal,
      montoTotal: total,
      idFormaPago: idFormaPago,
      host: franquicia,
      hostName: franquicia,
      tipoTarjeta: franquicia,
      tipoVenta: '',
      numeroTarjeta: ultimosDigitosTarjeta,
      loteAbierto: '1',
      nombreTH: '',
      aprobacion: numeroConfirmacion,
      idTerminal: '',
      numeroReferencia: numeroRecibo,
      codigoReferencia: numeroRecibo,
      idComercio: bin.toString(),
      diferidoyQuickPayment: '',
      reservado: '',
      archivoFirma: '',
      tvr: '',
      tsi: '',
      idCashBack: 0,
      anulada: false,
      multiplesVentas: false,
    );

    return result;
  }
}
